---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

    - name: Check git version
      command: git --version
      register: git_version_result

    - name: Display git version
      debug:
        msg: "{{ git_version_result.stdout }}"