---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  environment: "{{ environment_vars }}"

  tasks:
    - name: Ping using zos_ping
      zos_ping:
      register: zos_ping_result

    - name: Response from zos_ping
      debug:
        msg: "{{ zos_ping_result }}"

    - name: Check git version
      command: git --version
      register: git_version_result

    - name: Display git version
      debug:
        msg: "{{ git_version_result.stdout }}"

    - name: Pull latest code from repository
      git:
        repo: "git@github.com:benjaminthompson1/dbb-zappbuild.git"
        dest: "/u/ibmuser/zGit-Repositories/dbb-zappbuild"
        version: 'HEAD'
        accept_hostkey: yes  # Only if you're sure about accepting any hostkey, otherwise ensure the key is in known_hosts
        key_file: "/u/ibmuser/.ssh/github_rsa"  # Optional, if you want to specify a non-default private key
        update: yes