# GitHub Action: Run DBB on z25c
# This workflow triggers a series of jobs to handle database building (DBB) processes on z25c.

name: Run DBB on z25c

# Trigger:
# The workflow can be manually initiated from the GitHub Actions user interface.
on:
  workflow_dispatch:

jobs:
  # Job: Transfer to RHEL
  # Purpose:
  # - This job focuses on tasks related to the RHEL environment.
  # - It checks out the repository, lists directory contents for debugging purposes, and uses Ansible for file transfers.
  transfer-RHEL:
    # Execution Environment:
    # The tasks in this job are executed on a machine or container with a RHEL operating system.
    runs-on: RHEL

    steps:
      # Step 1: Repository Checkout
      # It retrieves the current code state from the repository and places it in the runner's workspace.
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Directory Listing
      # For debugging, it provides a snapshot of the files and directories currently in the runner's workspace.
      - name: List current directory contents
        run: ls -al

      # Step 3: Ansible Playbook Execution
      # This step executes an Ansible playbook which is responsible for transferring files and executing other tasks.
      # The playbook and inventory file paths are specified relative to the root of the repository.
      - name: DBB complie COBOL program using Ansible
        run: ansible-playbook -i .github/ansible/inventories/inventory.yml .github/ansible/zos_git_sync_and_dbb_run.yml -vvv